apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
spec:
  dnsNames:
    - new-prod-shark.ashwingowda.com
    - new-prod-shark-preview.ashwingowda.com
  secretName: new-prod-selfsigned-cert-tls
  issuerRef:
    name: new-prod-selfsigned-issuer
  # subject:
  #   organizations:
  #     - "Ashwin Gowda Inc."
  #   countries:
  #     - "IN"
  #   organizationalUnits:
  #     - "IT Department"
  #   localities:
  #     - "Bengaluru"
  #   provinces:
  #     - "Karnataka"
