apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
spec:
  dnsNames:
    - prod-shark.ashwingowda.com
    - prod-shark-preview.ashwingowda.com
  secretName: new-prod-selfsigned-cert-tls
  issuerRef:
    name: new-prod-selfsigned-issuer
