apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: new-prod-app
  namespace: argocd
spec:
  destination:
    namespace: new-prod
    server: https://kubernetes.default.svc
  project: new-prod
  source:
    path: new-prod
    repoURL: https://github.com/akm-devops/argo-labs.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
