apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: staging-selfsigned-cert
  namespace: staging
spec:
  dnsNames:
    - vote.ashwingowda.com
    - vote-preview.ashwingowda.com
  secretName: staging-selfsigned-cert-tls
  issuerRef:
    name: staging-selfsigned-issuer
