apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rollouts-selfsigned-cert
  namespace: argo-rollouts
spec:
  dnsNames:
    - rollouts.ashwingowda.com
  secretName: rollouts-selfsigned-cert-tls
  issuerRef:
    name: rollouts-selfsigned-issuer
