apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kube-prom-selfsigned-cert
  namespace: monitoring
spec:
  dnsNames:
    - prometheus.ashwingowda.com
    - grafana.ashwingowda.com
  secretName: kube-prom-selfsigned-cert-tls
  issuerRef:
    name: kube-prom-selfsigned-issuer
  subject:
    organizations:
      - "Ashwin Gowda Inc."
    countries:
      - "IN"
    organizationalUnits:
      - "DevOps"
    localities:
      - "Bengaluru"
    provinces:
      - "Karnataka"
