apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- rollout.yaml
- service.yaml
- preview-service.yaml
- issuer.yaml
- gtw.yaml
- httproute.yaml
- httproute-preview.yaml
images:
- name: ashwinkmgowda/nodejs-image-demo
  newName: ashwinkmgowda/nodejs-image-demo
  newTag: "40"
